$(document).ready(
    ()=>{

    }
)

const nav = {
    page:{
        ot:()=>{
            $("#mainArticle").html(pages.ot);
        },
        day01:()=>{
            $("#mainArticle").html(pages.day01);
        },
        day02:()=>{
            $("#mainArticle").html(pages.day02);
        },
        day03:()=>{
            $("#mainArticle").html(pages.day03);
        },
        day04:()=>{
            $("#mainArticle").html(pages.day04);
        },
        day05:()=>{
            $("#mainArticle").html(pages.day05);
        },
        day06:()=>{
            $("#mainArticle").html(pages.day06);
        },
        day07:()=>{
            $("#mainArticle").html(pages.day07);
        }
    },
    vocabs:{
        day01:()=>{
            $("#mainArticle").html(vocabs.day01);
            funcs.renderVocabList(vocab_db[0].vocabs,"list1","list2");
        },
        day02:()=>{
            $("#mainArticle").html(vocabs.day02);
            funcs.renderVocabList(vocab_db[1].vocabs,"list1","list2");
        },
        day03:()=>{
            $("#mainArticle").html(vocabs.day03);
            funcs.renderVocabList(vocab_db[2].vocabs,"list1","list2");
        },
        day04:()=>{
            $("#mainArticle").html(vocabs.day04);
            funcs.renderVocabList(vocab_db[3].vocabs,"list1","list2");
        },
        day05:()=>{
            $("#mainArticle").html(vocabs.day05);
            funcs.renderVocabList(vocab_db[4].vocabs,"list1","list2");
        },
        day06:()=>{
            $("#mainArticle").html(vocabs.day06);
        }
    },
    quiz:{
        day01:()=>{
            $("#mainArticle").html(quizes.day01);
        },
        day02:()=>{
            $("#mainArticle").html(quizes.day02);
        }
    }
}